version: '3.0'

services:
  main:
    container_name: main
    image: janekaz/game-jam-server-main:latest
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
      - /home/user/.postgresql/root.crt:/home/user/.postgresql/root.crt
    ports:
      - 5000:5000
      - 9229:9229
    command: npm run start
    depends_on:
      - postgres
    restart: always
  postgres:
    container_name: postgres
    image: janekaz/postgres:14
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
